<?php 
if (!defined(JZ_SECURE_ACCESS)) die ('Security breach detected.');

// Are they upgrading or not?
@include($include_path. 'install/defaultsettings.php');
@include($include_path. 'settings.php');

$content  = "<?php\n";
$content .= '     // Master Settings'. "\n";
$content .= '     $config_version = "'. $version. '";'. "\n";
$content .= '     $install_complete = "yes";'. "\n";
$content .= "\n";

$content .= '     // System Settings'. "\n";
$content .= '     $hierarchy = "'. $hierarchy.'";'. "\n";
$content .= '     $root_dir = "'. $root_dir. '";'. "\n";
$content .= '     $media_dirs = "'. $media_dirs. '";'. "\n";
$content .= '     $web_dirs = "";' . "\n";
$content .= '     $cms_type = "'. $cms_type. '";' . "\n";
$content .= '     $backend = "'. $backend. '";' . "\n";
$content .= '     $default_importer = "'. $default_importer. '";' . "\n";
$content .= '     $live_update = "'. $live_update. '";' . "\n";
$content .= '     $allow_filesystem_modify = "'. $allow_filesystem_modify. '";' . "\n";
$content .= '     $allow_id3_modify = "'. $allow_id3_modify. '";' . "\n";
$content .= '     $audio_types = "'. $audio_types. '";' . "\n";
$content .= '     $video_types = "'. $video_types. '";' . "\n";
$content .= '     $playlist_types = "'. $playlist_types. '";' . "\n";
$content .= '     $ext_graphic = "'. $ext_graphic. '";' . "\n";
$content .= '     $track_num_seperator = "'. $track_num_seperator. '";' . "\n";
$content .= '     $date_format = "'. $date_format. '";' . "\n";
$content .= '     $short_date = "'. $short_date. '";' . "\n";
$content .= '     $gzip_handler = "'. $gzip_handler. '";' . "\n";
$content .= '     $ssl_stream = "'. $ssl_stream. '";' . "\n";
$content .= '     $protocols = "'. $protocols. '";' . "\n";
$content .= '     $media_lock_mode = "'. $media_lock_mode. '";' . "\n";
$content .= '     $enable_podcast = "'. $enable_podcast. '";' . "\n";
$content .= '     $enable_podcast_subscribe = "'. $enable_podcast_subscribe. '";' . "\n";
$content .= '     $podcast_folder = "'. $podcast_folder. '";' . "\n";
$content .= '     $enable_logging = "'. $enable_logging. '";' . "\n";
$content .= '     $enable_shopping = "'. $enable_shopping. '";' . "\n";		
$content .= '     $secure_urls = "'. $secure_urls. '";' . "\n";
$content .= '     $enable_favorites = "'. $enable_favorites. '";' . "\n";
$content .= '     $enable_page_caching = "'. $enable_page_caching. '";' . "\n";		
$content .= '     $cache_age_days = "'. $cache_age_days. '";' . "\n";		
$content .= '     $gzip_page_cache = "'. $gzip_page_cache. '";' . "\n";				
$content .= '     $security_key = "'. $security_key. '";' . "\n";
$content .= '     $enable_query_cache = "'. $enable_query_cache. '";' . "\n";		
$content .= "\n";

$content .= '     // Playlist Settings' . "\n";
$content .= '     $enable_playlist = "'. $enable_playlist. '";' . "\n";
$content .= '     $playlist_ext = "'. $playlist_ext. '";' . "\n";
$content .= '     $use_ext_playlists = "'. $use_ext_playlists. '";' . "\n";
$content .= '     $asx_file_types = "'. $asx_file_types. '";' . "\n";
$content .= '     $asx_show_trackdetail = "'. $asx_show_trackdetail . '";' . "\n";
$content .= '     $max_playlist_length = "'. $max_playlist_length. '";' . "\n";
$content .= '     $random_play_amounts = "'. $random_play_amounts. '";' . "\n";
$content .= '     $default_random_count = "'. $default_random_count. '";' . "\n";
$content .= '     $default_random_type = "'. $default_random_type. '";' . "\n";
$content .= '     $embedded_player = "'. $embedded_player. '";' . "\n";
$content .= '     $enable_audioscrobbler = "'. $enable_audioscrobbler. '";' . "\n";
$content .= '     $as_override_user = "'. $as_override_user. '";' . "\n";
$content .= '     $as_override_pass = "'. $as_override_pass. '";' . "\n";
$content .= '     $as_override_all = "'. $as_override_all. '";' . "\n";
$content .= '     $as_max_retry = "'. $as_max_retry. '";' . "\n";
$content .= "\n";

$content .= '     // Display Settings' . "\n";
$content .= '     $site_title = "'. $site_title. '";' . "\n";
$content .= '     $jinzora_skin = "'. $jinzora_skin. '";' . "\n";
$content .= '     $frontend = "'. $frontend. '";' . "\n";
$content .= '     $jz_lang_file = "'. $jz_lang_file. '";' . "\n";
$content .= '     $allow_lang_choice = "'. $allow_lang_choice. '";' . "\n";
$content .= '     $allow_style_choice = "'. $allow_style_choice. '";' . "\n";
$content .= '     $allow_interface_choice = "'. $allow_interface_choice. '";' . "\n";
$content .= '     $show_loggedin_level = "'. $show_loggedin_level. '";' . "\n";
$content .= '     $help_access = "'. $help_access. '";' . "\n";
$content .= '     $artist_truncate = "'. $artist_truncate. '";' . "\n";
$content .= '     $quick_list_truncate = "'. $quick_list_truncate. '";' . "\n";
$content .= '     $album_name_truncate = "'. $album_name_truncate. '";' . "\n";
$content .= '     $show_page_load_time = "'. $show_page_load_time. '";' . "\n";
$content .= '     $show_sub_numbers = "'. $show_sub_numbers. '";' . "\n";
$content .= '     $sort_by_year = "'. $sort_by_year. '";' . "\n";
$content .= '     $num_other_albums = "'. $num_other_albums. '";' . "\n";
$content .= '     $header_drops = "'. $header_drops. '";' . "\n";
$content .= '     $genre_drop = "'. $genre_drop. '";' . "\n";
$content .= '     $artist_drop = "'. $artist_drop. '";' . "\n";
$content .= '     $album_drop = "'. $album_drop. '";' . "\n";
$content .= '     $song_drop = "'. $song_drop. '";' . "\n";
$content .= '     $quick_drop = "'. $quick_drop. '";' . "\n";
$content .= '     $days_for_new = "'. $days_for_new. '";' . "\n";
$content .= '     $hide_id3_comments = "'. $hide_id3_comments. '";' . "\n";
$content .= '     $show_all_checkboxes = "'. $show_all_checkboxes. '";' . "\n";
$content .= '     $status_blocks_refresh = "'. $status_blocks_refresh. '";' . "\n";
$content .= '     $compare_ignores_the = "'. $compare_ignores_the. '";' . "\n";
$content .= '     $handle_compilations = "'. $handle_compilations. '";' . "\n";
$content .= '     $embedded_header = "'. $embedded_header. '";' . "\n";
$content .= '     $embedded_footer = "'. $embedded_footer. '";' . "\n";
$content .= '     $who_is_where_height = "'. $who_is_where_height. '";' . "\n";
$content .= "\n";

$content .= '     // Image Settings' . "\n";
$content .= '     $resize_images = "'. $resize_images. '";' . "\n";
$content .= '     $keep_porportions = "'. $keep_porportions. '";' . "\n";
$content .= '     $auto_search_art = "'. $auto_search_art. '";' . "\n";
$content .= '     $create_blank_art = "'. $create_blank_art. '";' . "\n";
$content .= '     $default_art = "'. $default_art. '";' . "\n";
$content .= "\n";

$content .= '     // Groupware Settings' . "\n";
$content .= '     $enable_discussion = "'. $enable_discussion. '";' . "\n";
$content .= '     $enable_requests = "'. $enable_requests. '";' . "\n";
$content .= '     $enable_ratings = "'. $enable_ratings. '";' . "\n";
$content .= '     $rating_weight = "'. $rating_weight. '";' . "\n";
$content .= '     $track_plays = "'. $track_plays. '";' . "\n";
$content .= '     $display_downloads = "'. $display_downloads. '";' . "\n";
$content .= '     $secure_links = "'. $secure_links. '";' . "\n";
$content .= '     $user_tracking_display = "'. $user_tracking_display. '";' . "\n";
$content .= '     $user_tracking_age = "'. $user_tracking_age. '";' . "\n";
$content .= '     $disable_random = "'. $disable_random. '";' . "\n";
$content .= '     $info_level = "'. $info_level. '";' . "\n";
$content .= '     $track_play_only = "'. $track_play_only. '";' . "\n";
$content .= '     $allow_clips = "'. $allow_clips. '";' . "\n";
$content .= '     $clip_length = "'. $clip_length. '";' . "\n";
$content .= '     $clip_start = "'. $clip_start. '";' . "\n";
$content .= "\n";

$content .= '     // Charts and Random Album Settings' . "\n";
$content .= '     $display_charts = "'. $display_charts. '";' . "\n";
$content .= '     $chart_types = "'. $chart_types. '";' . "\n";
$content .= '     $num_items_in_charts = "'. $num_items_in_charts. '";' . "\n";
$content .= '     $random_albums = "'. $random_albums. '";' . "\n";
$content .= '     $random_per_slot = "'. $random_per_slot. '";' . "\n";
$content .= '     $random_rate = "'. $random_rate. '";' . "\n";
$content .= '     $random_art_size = "'. $random_art_size. '";' . "\n";
$content .= '     $rss_in_charts = "'. $rss_in_charts. '";' . "\n";
$content .= '     $chart_timeout_days = "'. $chart_timeout_days. '";' . "\n";
$content .= "\n";

$content .= '     // Resampling' . "\n";
$content .= '     $allow_resample = "'. $allow_resample. '";' . "\n";
$content .= '     $force_resample = "'. $force_resample. '";' . "\n";
$content .= '     $default_resample = "'. $default_resample. '";' . "\n";
$content .= '     $resampleRates = "'. $resampleRates. '";' . "\n";
$content .= '     $path_to_lame = "'. $path_to_lame. '";' . "\n";
$content .= '     $path_to_flac = "'. $path_to_flac. '";' . "\n";
$content .= '     $path_to_mpc = "'. $path_to_mpc. '";' . "\n";
$content .= '     $path_to_wavunpack = "'. $path_to_wavunpack. '";' . "\n";
$content .= '     $path_to_oggdec = "'. $path_to_oggdec. '";' . "\n";
$content .= '     $path_to_oggenc = "'. $path_to_oggenc. '";' . "\n";
$content .= '     $path_to_mpcenc = "'. $path_to_mpcenc. '";' . "\n";
$content .= '     $path_to_wavpack = "'. $path_to_wavpack. '";' . "\n";
$content .= '     $path_to_wmadec = "'. $path_to_wmadec. '";' . "\n";
$content .= '     $path_to_faad = "'. $path_to_faad. '";' . "\n";
$content .= '     $path_to_shn = "'. $path_to_shn. '";' . "\n";
$content .= '     $path_to_ofr = "'. $path_to_ofr. '";' . "\n";
$content .= '     $path_to_macpipe = "'. $path_to_macpipe. '";' . "\n";
$content .= '     $path_to_mplayer = "'. $path_to_mplayer. '";' . "\n";
$content .= '     $mplayer_opts = "'. $mplayer_opts. '";' . "\n";
$content .= '     $lame_cmd = "'. $lame_cmd. '";' . "\n";
$content .= '     $lame_opts = "'. $lame_opts. '";' . "\n";
$content .= '     $always_resample = "'. $always_resample. '";' . "\n";
$content .= '     $always_resample_rate = "'. $always_resample_rate. '";' . "\n";
$content .= '     $allow_resample_downloads = "'. $allow_resample_downloads. '";' . "\n";
$content .= '     $resample_cache_size = "'. $resample_cache_size. '";' . "\n";
$content .= '     $no_resample_subnets = "'. $no_resample_subnets. '";' . "\n";
$content .= "\n";

$content .= '     // Download Settings' . "\n";
$content .= '     $multiple_download_mode = "'. $multiple_download_mode. '";' . "\n";
$content .= '     $single_download_mode = "'. $single_download_mode. '";' . "\n";
$content .= "\n";

$content .= '     // Email Settings' . "\n";
$content .= '     $allow_send_email = "'. $allow_send_email. '";' . "\n";
$content .= '     $email_from_address = "'. $email_from_address. '";' . "\n";
$content .= '     $email_from_name = "'. $email_from_name. '";' . "\n";
$content .= '     $email_server = "'. $email_server. '";' . "\n";
$content .= "\n";

$content .= '     // Jukebox Settings' . "\n";
$content .= '     $jukebox = "'. $jukebox. '";' . "\n";
$content .= '     $jukebox_display = "'. $jukebox_display. '";' . "\n";
$content .= '     $jukebox_default_addtype = "'. $jukebox_default_addtype. '";' . "\n";
$content .= '     $default_jukebox = "'. $default_jukebox. '";' . "\n";
$content .= '     $home_jukebox_subnets = "'. $home_jukebox_subnets. '";' . "\n";
$content .= '     $home_jukebox_id = "' . $home_jukebox_id. '";' . "\n";
$content .= '     $jb_volumes = "'. $jb_volumes. '";' . "\n";
$content .= "\n";

$content .= '     // Keyword Settings' . "\n";
$content .= '     $keyword_radio = "'. $keyword_radio. '";' . "\n";
$content .= '     $keyword_random = "'. $keyword_random. '";' . "\n";
$content .= '     $keyword_play = "'. $keyword_play. '";' . "\n";
$content .= '     $keyword_track = "'. $keyword_track. '";' . "\n";
$content .= '     $keyword_album = "'. $keyword_album. '";' . "\n";
$content .= '     $keyword_artist = "'. $keyword_artist. '";' . "\n";
$content .= '     $keyword_genre = "'. $keyword_genre. '";' . "\n";
$content .= '     $keyword_lyrics = "'. $keyword_lyrics. '";' . "\n";
$content .= '     $keyword_limit = "'. $keyword_limit. '";' . "\n";
$content .= '     $keyword_id = "'. $keyword_id. '";' . "\n";
$content .= "\n";

$content .= '     // Audioscrobbler Settings' . "\n";
$content .= '     $audioscrobbler_user = "'. $audioscrobbler_user. '";' . "\n";
$content .= '     $audioscrobbler_pass = "'. $audioscrobbler_pass. '";' . "\n";

?>
